name: quickjs

on:
  [push]
jobs:
  windows:
    name: windows
    runs-on: windows-latest
    if: "contains(toJSON(github.event.commits.*.message), '[build windows]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64
    - name: Build
      run: |
         cd native
         ./build.bat
    - name: Test
      run: |
         mvn --no-transfer-progress -q -B -DskipTests package
         mvn --no-transfer-progress test
  mac:
    name: macos
    runs-on: macos-10.15
    if: "contains(toJSON(github.event.commits.*.message), '[build macos]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64
    - name: Build
      run: |
         cd native
         mkdir build
         cd build
         cmake .. -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_BUILD_TYPE=Release
         make
    - name: Test
      run: |
         mvn --no-transfer-progress -q -B -DskipTests package
         mvn --no-transfer-progress test